import { CaseData, ComplianceRule, ClausePattern, LineageEvent, LearningPackage, GeneratedReport } from '../types/tdv';

export const initialRules: ComplianceRule[] = [
  {
    id: 'R-SAN-004',
    version: 'v2.4',
    title: 'Mandatory BIMCO Sanctions Clause 2024',
    sourceRef: 'BIMCO Sanctions Clause / EU Sanctions Reg. 833/2014',
    domain: 'Sanctions',
    jurisdiction: 'Global / EU / UK',
    severity: 'Critical',
    logicDescription: 'Requires explicit warranties regarding SDN list, EU/UK/US Sanctioned entities, and vessel AIS tracking compliance.',
    modelClause: 'The Charterers warranty that neither they, nor the sub-charterers, shippers, receivers or cargo owners are subject to sanctions administered by OFAC, EU, UK, or UN. Charterers shall maintain AIS operational at all times.',
    validFrom: '2024-01-01',
    status: 'Active'
  },
  {
    id: 'R-ENV-012',
    version: 'v1.1',
    title: 'EU ETS Allocation & Carbon Allowance Pass-Through Clause',
    sourceRef: 'EU Directive 2003/87/EC (EU ETS Expansion)',
    domain: 'Environmental',
    jurisdiction: 'EU / EEA Ports',
    severity: 'High',
    logicDescription: 'Mandates charterer liability for EUA allowances incurred during voyage within or into EU waters.',
    modelClause: 'Charterers shall surrender to Owners the required quantity of EU Allowances (EUAs) corresponding to the emissions generated by the Vessel during the Charter Period within 10 days of Owners request.',
    validFrom: '2024-01-01',
    status: 'Active'
  },
  {
    id: 'R-COM-008',
    version: 'v3.0',
    title: 'Demurrage Claim Notice Time-Bar & Document Submission',
    sourceRef: 'English Law Commercial Norms / NYPE 93 Rider',
    domain: 'Commercial',
    jurisdiction: 'English Law',
    severity: 'Medium',
    logicDescription: 'Checks that demurrage notice requirement aligns between recap and base form, with minimum 30-day submission window.',
    modelClause: 'Owners shall notify Charterers of any demurrage claim within 30 consecutive days after completion of discharge, failing which the claim shall be deemed waived and time-barred.',
    validFrom: '2023-06-15',
    status: 'Active'
  },
  {
    id: 'R-LIAB-002',
    version: 'v1.0',
    title: 'Hague-Visby Rules Incorporation & Limitation Cap',
    sourceRef: 'Hague-Visby Rules 1968 / SDR Protocol 1979',
    domain: 'Cargo Liability',
    jurisdiction: 'International Maritime Law',
    severity: 'High',
    logicDescription: 'Ensures cargo liability is governed by Hague-Visby with SDR limitation rather than superseded 1924 Hague Rules.',
    modelClause: 'This Charter Party and any Bill of Lading issued hereunder shall have effect subject to the Hague-Visby Rules as enacted in the country of shipment.',
    validFrom: '2022-01-01',
    status: 'Active'
  }
];

export const initialPatterns: ClausePattern[] = [
  {
    id: 'CP-SAN-801',
    version: 'v1.3',
    category: 'Sanctions & Trade Controls',
    canonicalText: 'Charterers warrant that vessel shall not call at sanctioned ports nor engage with listed designated entities.',
    disputeRate: 0.03,
    successRate: 0.96,
    impactBand: 'Critical',
    medianImpactUsd: 850000,
    confidence: 0.94,
    kAnonymityLevel: 12,
    status: 'Active'
  },
  {
    id: 'CP-ETS-402',
    version: 'v1.0',
    category: 'Emissions & EU ETS',
    canonicalText: 'EU ETS allowance transfer mechanism with monthly reconciliation and verified MARPOL logbook reporting.',
    disputeRate: 0.08,
    successRate: 0.91,
    impactBand: 'High',
    medianImpactUsd: 240000,
    confidence: 0.89,
    kAnonymityLevel: 8,
    status: 'Active'
  },
  {
    id: 'CP-DEM-205',
    version: 'v2.1',
    category: 'Demurrage & Laytime',
    canonicalText: 'Demurrage rate $18,500/day pro rata with 60-day time bar and mandatory supporting SOF documentation.',
    disputeRate: 0.14,
    successRate: 0.88,
    impactBand: 'Moderate',
    medianImpactUsd: 65000,
    confidence: 0.92,
    kAnonymityLevel: 15,
    status: 'Active'
  }
];

export const initialCases: CaseData[] = [
  {
    id: 'CASE-2026-089',
    title: 'MV Tegrity Endeavour — Dry Bulk Voyage Charter',
    trade: 'Dry Bulk (Iron Ore)',
    charterType: 'Voyage Charter',
    effectiveDate: '2026-10-08',
    status: 'Analyzed',
    riskScore: 78,
    riskBand: 'Critical',
    owner: 'Ashwani Sethi (Legal Lead)',
    documents: [
      {
        id: 'DOC-101',
        name: 'NYPE_93_Base_Charter_Party.pdf',
        type: 'Charter Party',
        fileUri: '/documents/NYPE_93_Base_Charter_Party.pdf',
        sha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        ocrQuality: 98,
        pages: 34,
        precedenceOrder: 1,
        uploadedAt: '2026-10-08T10:14:00Z'
      },
      {
        id: 'DOC-102',
        name: 'Rider_Clauses_Special_Terms.docx',
        type: 'Rider Clause',
        fileUri: '/documents/Rider_Clauses_Special_Terms.docx',
        sha256: 'f4c5d6e7a8b90123456789abcdef0123456789abcdef0123456789abcdef0123',
        ocrQuality: 100,
        pages: 12,
        precedenceOrder: 2,
        uploadedAt: '2026-10-08T10:15:30Z'
      },
      {
        id: 'DOC-103',
        name: 'Fixture_Recap_Confirmation.pdf',
        type: 'Fixture Recap',
        fileUri: '/documents/Fixture_Recap_Confirmation.pdf',
        sha256: '9876543210fedcba0123456789abcdef0123456789abcdef0123456789abcdef',
        ocrQuality: 96,
        pages: 3,
        precedenceOrder: 3,
        uploadedAt: '2026-10-08T10:16:10Z'
      }
    ],
    extractedFields: [
      { id: 'EF-1', name: 'Charterer', value: 'Tegrity Global Shipping Pte Ltd', confidence: 0.98 },
      { id: 'EF-2', name: 'Vessel Name & DWT', value: 'MV Tegrity Endeavour (180,000 MT DWT)', confidence: 0.99 },
      { id: 'EF-3', name: 'Load Port / Discharge Port', value: 'Port Hedland, WA / Qingdao, China', confidence: 0.96 },
      { id: 'EF-4', name: 'Freight Rate', value: 'USD 24.50 per Metric Ton FIOST', confidence: 0.97 },
      { id: 'EF-5', name: 'Demurrage Rate', value: 'USD 18,500 / day pro rata', confidence: 0.99 },
      { id: 'EF-6', name: 'Laytime Allowance', value: '120 Hours Total Weather Working Days', confidence: 0.95 },
      { id: 'EF-7', name: 'Governing Law & Arbitration', value: 'English Law / LMAA Arbitration London', confidence: 0.98 }
    ],
    clauses: [
      {
        id: 'CLS-01',
        docId: 'DOC-101',
        number: 'Clause 24',
        heading: 'Sanctions & Trading Restrictions',
        text: 'Vessel shall not be required to enter any port or place where sanctions are imposed by United Nations, provided Charterers notify Master within reasonable time.',
        span: { start: 1420, end: 1680, page: 18 },
        category: 'Sanctions & Trade Controls'
      },
      {
        id: 'CLS-02',
        docId: 'DOC-102',
        number: 'Rider Cl. 45',
        heading: 'Demurrage & Time Bar',
        text: 'All demurrage claims must be submitted to Charterers together with Statement of Facts and signed Laytime Statement within 14 calendar days of completion of discharge.',
        span: { start: 540, end: 790, page: 4 },
        category: 'Demurrage & Laytime',
        amendsClauseId: 'CLS-03'
      },
      {
        id: 'CLS-03',
        docId: 'DOC-101',
        number: 'Clause 12',
        heading: 'Base Form Demurrage Terms',
        text: 'Demurrage at load and discharge ports shall be paid by Charterers at the rate of USD 18,500 per day within 30 days of invoice.',
        span: { start: 890, end: 1040, page: 9 },
        category: 'Demurrage & Laytime'
      },
      {
        id: 'CLS-04',
        docId: 'DOC-102',
        number: 'Rider Cl. 52',
        heading: 'Environmental Emissions & EU ETS',
        text: 'Owners and Charterers agree to cooperate in good faith regarding emissions monitoring under MARPOL Annex VI.',
        span: { start: 2100, end: 2310, page: 8 },
        category: 'Emissions & EU ETS'
      }
    ],
    findings: [
      {
        id: 'FND-101',
        runId: 'RUN-2026-001',
        clauseId: 'CLS-01',
        docId: 'DOC-101',
        type: 'Compliance gap',
        status: 'Open',
        ruleIds: ['R-SAN-004'],
        patternIds: ['CP-SAN-801'],
        severity: 'Critical',
        probability: 0.85,
        exposureUsd: { low: 400000, likely: 650000, high: 1200000 },
        findingScore: 88,
        confidence: 0.94,
        recommendationAction: 'amend',
        proposedText: 'Replace Clause 24 with mandatory BIMCO Sanctions Clause 2024 containing explicit SDN warranties and continuous AIS operational commitments.',
        rationale: 'Current clause lacks explicit warranties for sub-charterers and AIS tracking compliance, exposing vessel to EU/UK sanctions regulatory enforcement.',
        estimatedEffort: 2
      },
      {
        id: 'FND-102',
        runId: 'RUN-2026-001',
        clauseId: 'CLS-02',
        docId: 'DOC-102',
        type: 'Conflict',
        status: 'Open',
        ruleIds: ['R-COM-008'],
        patternIds: ['CP-DEM-205'],
        severity: 'High',
        probability: 0.65,
        exposureUsd: { low: 50000, likely: 120000, high: 220000 },
        findingScore: 72,
        confidence: 0.91,
        recommendationAction: 'amend',
        proposedText: 'Amend Rider Cl. 45 time-bar window from 14 days to 30 days after discharge to align with Fixture Recap precedence.',
        rationale: 'Fixture Recap specifies 30 days while Rider Cl. 45 specifies 14 days. Precedence ambiguity creates high risk of demurrage claim waiver under English Law.',
        estimatedEffort: 1
      },
      {
        id: 'FND-103',
        runId: 'RUN-2026-001',
        clauseId: 'CLS-04',
        docId: 'DOC-102',
        type: 'Safeguard opportunity',
        status: 'Open',
        ruleIds: ['R-ENV-012'],
        patternIds: ['CP-ETS-402'],
        severity: 'Medium',
        probability: 0.45,
        exposureUsd: { low: 20000, likely: 55000, high: 110000 },
        findingScore: 54,
        confidence: 0.88,
        recommendationAction: 'add',
        proposedText: 'Insert BIMCO EU ETS Allowance Transfer Clause allocating mandatory EUA surrender within 10 days of request.',
        rationale: 'Vessel is routed into EU waters; generic good-faith cooperation wording leaves EUA costs unassigned, risking $55,000 unrecovered ETS liability.',
        estimatedEffort: 2
      }
    ],
    scenarios: [
      {
        id: 'SCN-01',
        name: 'Baseline (Unmodified Analysis)',
        changes: {},
        caseScore: 78,
        expectedLossUsd: 825000,
        createdBy: 'TDV Validation Engine',
        createdAt: '2026-10-08T10:20:00Z'
      }
    ]
  }
];

export const initialLineage: LineageEvent[] = [
  {
    id: 'EVT-1001',
    prevHash: '0000000000000000000000000000000000000000000000000000000000000000',
    hash: 'a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0',
    actor: 'Submitter (Ashwani Sethi)',
    role: 'Submitter',
    action: 'CASE_CREATED',
    objectRef: 'CASE-2026-089',
    diff: 'Created case "MV Tegrity Endeavour — Dry Bulk Voyage Charter"',
    timestamp: '2026-10-08T10:14:00Z'
  },
  {
    id: 'EVT-1002',
    prevHash: 'a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0',
    hash: 'b2c3d4e5f6a17890123456789abcdef0123456789abcdef0123456789abcdef1',
    actor: 'Ingestion Service',
    role: 'Platform Auditor',
    action: 'DOCUMENTS_INGESTED',
    objectRef: 'DOC-101, DOC-102, DOC-103',
    diff: '3 documents uploaded. OCR quality 98%. Extracted 7 key fields.',
    timestamp: '2026-10-08T10:16:30Z'
  },
  {
    id: 'EVT-1003',
    prevHash: 'b2c3d4e5f6a17890123456789abcdef0123456789abcdef0123456789abcdef1',
    hash: 'c3d4e5f6a1b27890123456789abcdef0123456789abcdef0123456789abcdef2',
    actor: 'F4 Validation Engine',
    role: 'Platform Auditor',
    action: 'ANALYSIS_RUN_COMPLETED',
    objectRef: 'RUN-2026-001',
    diff: 'Ran 4 rule packs against 3 documents. Generated 3 findings. Case score: 78 (Critical).',
    timestamp: '2026-10-08T10:20:00Z'
  }
];

export const initialLearningQueue: LearningPackage[] = [
  {
    id: 'PKG-801',
    sourceDecisionId: 'DEC-2026-042',
    clauseCategory: 'Sanctions & Trade Controls',
    anonymizedPayload: 'Clause wording tokenized: "Charterers warrant [PARTY_ANON] compliance with OFAC/EU sanctions and continuous AIS uptime."',
    privacyCheckPassed: true,
    kLevelAchieved: 8,
    proposedPatternId: 'CP-SAN-801',
    curatorAction: 'Pending'
  },
  {
    id: 'PKG-802',
    sourceDecisionId: 'DEC-2026-039',
    clauseCategory: 'Emissions & EU ETS',
    anonymizedPayload: 'Clause wording tokenized: "Monthly EUA surrender within 10 days of request based on verified logbook emissions."',
    privacyCheckPassed: true,
    kLevelAchieved: 6,
    proposedPatternId: 'CP-ETS-402',
    curatorAction: 'Pending'
  }
];

export const initialReports: GeneratedReport[] = [
  {
    id: 'RPT-101',
    decisionId: 'DEC-2026-042',
    type: 'Executive Summary',
    createdAt: '2026-10-08T11:30:00Z',
    fileUri: '/reports/Executive_Summary_CASE-2026-089.pdf',
    redacted: false,
    shareUrl: 'https://tdv.tegrity.ai/share/exp-8092a1'
  }
];
